# Generated by Django 3.1.5 on 2021-02-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210213_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
