# Generated by Django 3.1.5 on 2021-02-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210213_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, max_length=300),
        ),
    ]
